esphome:
  name: comelit
  friendly_name: comelit
  includes:
    - comelit.h

esp8266:
  board: d1_mini

# Enable logging
logger:
  #level: VERY_VERBOSE

ota:
  password: "----------------paste your ota password here---------------------"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Comelit Fallback Hotspot"
    password: "comelit"

captive_portal:
api:
  encryption:
    key: "----------------paste your encryption key here---------------------"
  services:
    - service: send_code
      variables:
        command: int
        address: int
      then:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 25kHz
            code: !lambda return comelit_encode(address, command);
        - homeassistant.service:
            service: logbook.log
            data:
              name: "Intercom:"
              entity_id: "binary_sensor.comelit_state"
            data_template:
              message: "Sent custom command {{ com }}, address {{ ind }}"
            variables:
              com: "return command;"
              ind: "return address;"

    - service: outer_door_opener
      then:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 25kHz
            code: !lambda return comelit_encode(1, 16);
        - homeassistant.service:
            service: logbook.log
            data:
              name: "Intercom:"
              entity_id: "binary_sensor.comelit_state"
              message: "open external door via home automation"

    - service: inner_door_opener
      then:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 25kHz
            code: !lambda return comelit_encode(1, 29);
        - homeassistant.service:
            service: logbook.log
            data:
              name: "Intercom:"
              entity_id: "binary_sensor.comelit_state"
              message: "open internal door by home automation"

    - service: gate_opener
      then:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 25kHz
            code: !lambda return comelit_encode(1, 16);
        - delay: 100ms
        - remote_transmitter.transmit_raw:
            carrier_frequency: 25kHz
            code: !lambda return comelit_encode(1, 29);
        - homeassistant.service:
            service: logbook.log
            data:
              name: "Intercom:"
              entity_id: "binary_sensor.comelit_state"
              message: "open both gates via home automation"

globals:
  - id: code
    type: int
    restore_value: no
    initial_value: "0"
  - id: address
    type: int
    restore_value: no
    initial_value: "0"
  - id: description
    type: std::string

binary_sensor:
  - platform: status
    id: status
    name: "status"
    icon: mdi:doorbell

remote_transmitter:
  pin: D1
  carrier_duty_percent: 50%

remote_receiver:
  pin:
    number: D6
    inverted: false
  #dump: raw
  idle: 10ms
  filter: 250us
  buffer_size: 3k
  on_raw:
    then:
      - lambda: |-
          id(code) = 0;
          id(address) = 0;
          ESP_LOGV("DEBUG", "LENGTH OF RECEIVED RAW CODE %u", size(x));
          char message[18];
          int bits = 0;
          if (size(x) == 38) {
            for (auto it = x.begin() + 1; it != x.end() -1; it+=2) {
              if (-*it < 2500 && -*it > 1000)
              {
                message[bits] = 0;
                bits += 1;
              }
              else if (-*it < 6200 && -*it > 3500)
              {
                message[bits] = 1;
                bits += 1;
              }
              if (bits == 18) {
                int sum = 0;
                int checksum = 0;
                for (int i = 0; i < 14; i++)
                {
                  if (message[i] == 1) sum++;
                }
                checksum = (message[17] * 8) + (message[16] * 4) + (message[15] * 2) + message[14];

                if (checksum == sum) {
                  int msgCode[6];
                  int msgAddr[8];
                  for (int j = 0; j < 14; j++)
                  {
                    if (j < 6) msgCode[j] = message[j];
                    else msgAddr[j - 6] = message[j];
                  }
                  id(code) = (msgCode[5] * 32) + (msgCode[4] * 16) + (msgCode[3] * 8) + (msgCode[2] * 4) + (msgCode[1] * 2) + msgCode[0];
                  id(address) = (msgAddr[7] * 128) + (msgAddr[6] * 64) + (msgAddr[5] * 32) + (msgAddr[4] * 16) + (msgAddr[3] * 8) + (msgAddr[2] * 4) + (msgAddr[1] * 2) + msgAddr[0];
                  if (id(code) < 63)
                  {
                    ESP_LOGD("DEBUG", "RECEIVED COMMAND = %i", id(code));
                    ESP_LOGD("DEBUG", "RECEIVED ADDRESS = %i", id(address));
                    ESP_LOGD("DEBUG", "CHECKSUM OK");
                    auto capi = new esphome::api::CustomAPIDevice();
                    capi->fire_homeassistant_event("esphome.comelit_received", {{"address", std::to_string(id(address))}, {"command", std::to_string(id(code))}});
                  } else {
                    id(code) = 0;
                    id(address) = 0;
                  }
                }
              }
            }
          }

      # ------------------------------------------------------------------------------------------------------------
      # DELETE THE FOLLOWING PART IF YOU DO NOT WANT TO GET A COMPLETE LOG OF ALL MESSAGES PASSING OVER THE BUS
      # ------------------------------------------------------------------------------------------------------------

      - if:
          condition:
            lambda: "return (id(code) > 0) && (id(address) > 0);"
          then:
            - lambda: |-
                std::string str = "";
                if (id(code) == 50){
                  str = "extension call " + to_string(id(address));
                } else if (id(code) == 16) {
                  str = "external door opening from inside " + to_string(id(address));
                } else if (id(code) == 20) {
                  str = "indoor video startup " + to_string(id(address));
                } else if (id(code) == 17) {
                  str = "indoor audio startup " + to_string(id(address));
                } else if (id(code) == 29) {
                  if (id(address) == 1) {
                    str = "staircase door opening A";
                  } else if (id(address) == 2) {
                    str = "staircase door opening B";
                  } else if (id(address) == 4) {
                    str = "staircase door opening C";
                  }
                }
                id(description) = str;
                id(code) = 0;
                id(address) = 0;
            - if:
                condition:
                  lambda: 'return id(description) != "";'
                then:
                  - logger.log:
                      format: "description code: %s"
                      args: ["id(description).c_str()"]
                  - homeassistant.service:
                      service: logbook.log
                      data:
                        name: "Intercom:"
                        entity_id: "binary_sensor.comelit_state"
                      data_template:
                        message: "{{ com }}"
                      variables:
                        com: "return id(description).c_str();"
                  - lambda: 'id(description) = "";'
#      - homeassistant.event:
#          event: esphome.comelit_raw
#          data:
#             code: !lambda '
#             std::string str = "";
#             for (auto it = x.begin(); it != x.end(); ++it)
#             {
#               str += to_string(*it);
#               if (it != x.end() - 1) str += ", ";
#             }
#             return esphome::to_string("[" + str + "]");'
